swagger: "2.0"
info:
  version: "0.0.1"
  title: Decentralized crypto-fund platform
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# schemes:
  # tip: remove http to make production-grade
  # - http
  # - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /contracts/{contractName}:
    x-swagger-router-controller: contracts
    get:
      description: Returns ABI and Bytecode of compiled contract
      operationId: getContractDetails
      tags: 
        - Contracts
      parameters:
        - name: contractName
          in: path
          description: The name of the contract
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ContractDetailsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /campaigns:
    x-swagger-router-controller: campaigns
    get:
      description: Returns all campaigns
      operationId: getCampaigns
      tags: 
        - Data
      responses:
        "200":
          description: Success
          schema:
            required:
              - data
            properties:
              data:
                type: array
                items: 
                  $ref: "#/definitions/Campaigns"
            
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

    post:
      description: Create a campaign
      operationId: createCampaign
      tags: 
        - Data
      parameters:
        - name: body
          in: body
          description: Create a new fundraising campaign
          required: true
          schema:
            $ref: "#/definitions/Campaign"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Campaign"
            
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /campaigns/{id}:
    x-swagger-router-controller: campaigns
    get:
      description: Get campaign details
      operationId: getCampaign
      tags: 
        - Data
      parameters:
        - name: id
          in: path
          description: The campaign id
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Campaign"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    
definitions:
  ErrorResponse:
    required:
      - error
      - message
    properties:
      error: 
        type: boolean
      message:
        type: string
      
  Campaigns:
    type: array
    items: 
      $ref: "#/definitions/Campaign"

  Campaign:
    required:
      - fundraiserContractAddress
      - beneficiaryAddress
      - endDate
      - conversionRate
      - description
      - minCap
    properties: 
      fundraiserContractAddress:
        type: string
      beneficiaryAddress:
        type: string
      endDate:
        type: number
      conversionRate:
        type: number
      description:
        type: string
      minCap:
        type: number

  ContractDetailsResponse:
    required:
      - bytecode
      - abi
    properties: 
      bytecode:
        type: string
      abi:
        type: array
        items: 
          $ref: "#/definitions/ABI"

  ABIInput:
    properties: 
      name:
        type: string
      type:
        type: string
  
  ABIOutput:
    properties: 
      name:
        type: string
      type:
        type: string
  ABI:
    properties: 
      constant:
        type: boolean
      name:
        type: string
      payable:
        type: boolean
      stateMutability:
        type: string
      type:
        type: string
      inputs:
        type: array
        items: 
          $ref: "#/definitions/ABIInput"
      outputs:
        type: array
        items: 
          $ref: "#/definitions/ABIOutput"