swagger: "2.0"
info:
  version: "0.0.1"
  title: Decentralized crypto-fund platform
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# schemes:
  # tip: remove http to make production-grade
  # - http
  # - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /contracts/campaign-token:
    x-swagger-router-controller: contracts
    post:
      description: Deploy campaign token
      operationId: deployCampaignToken
      tags: 
        - Contracts
      parameters:
        - name: body
          in: body
          description: Number of tokens to create
          required: true
          schema:
            $ref: "#/definitions/DeployCampaignTokenRequest"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ContractDeployedResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /contracts/campaign-fundraiser:
    x-swagger-router-controller: contracts
    post:
      description: Deploy campaign token fundraiser
      operationId: deployCampaignTokenFundraiser
      tags: 
        - Contracts
      parameters:
        - name: body
          in: body
          description: Fundraiser address
          required: true
          schema:
            $ref: "#/definitions/DeployCampaignTokenFundraiserRequest"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ContractDeployedResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /campaigns:
    x-swagger-router-controller: campaigns
    get:
      description: Returns all campaigns
      operationId: getCampaigns
      tags: 
        - Data
      responses:
        "200":
          description: Success
          schema:
            required:
              - data
            properties:
              data:
                type: array
                items: 
                  $ref: "#/definitions/Campaigns"
            
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

    post:
      description: Create a campaign
      operationId: addCampaign
      tags: 
        - Data
      parameters:
        - name: body
          in: body
          description: Create a new fundraising campaign
          required: true
          schema:
            $ref: "#/definitions/NewCampaignRequest"
      responses:
        "200":
          description: Success
            
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /campaigns/{id}:
    x-swagger-router-controller: campaigns
    get:
      description: Get campaign details
      operationId: getCampaign
      tags: 
        - Data
      parameters:
        - name: id
          in: path
          description: The campaign id
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Campaign"
            
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
    
  ErrorResponse:
    required:
      - error
      - message
    properties:
      error: 
        type: boolean
      message:
        type: string
      
  Campaigns:
    type: array
    items: 
      $ref: "#/definitions/Campaign"

  Campaign:
    required:
      - id
      - isActive
      - name
      - type
      - description
      - startDate
      - endDate
      - bonus
      - tokenName
      - conversionRate
      - tokensHardCap
      - beneficiaryAddress
      - campaignContractAddress
      - campaignContractABI
      - campaignDataHash
    properties: 
      id:
        type: string
      isActive:
        type: boolean
      name:
        type: string
      type:
        type: string
      description:
        type: string
      startDate:
        type: number
      endDate:
        type: number
      bonus:
        type: number
      tokenName:
        type: string
      conversionRate:
        type: number
      tokensHardCap:
        type: number
      beneficiaryAddress:
        type: string
      campaignContractAddress:
        type: string
      campaignContractABI:
        type: array
        items: 
          $ref: "#/definitions/ABI"
      campaignDataHash:
        type: string

  NewCampaignRequest:
    required:
      - name
      - type
      - description
      - startDate
      - endDate
      - bonus
      - tokenName
      - conversionRate
      - tokensHardCap
      - beneficiaryAddress
    properties: 
      name:
        type: string
      type:
        type: string
      description:
        type: string
      startDate:
        type: number
      endDate:
        type: number
      bonus:
        type: number
      tokenName:
        type: string
      conversionRate:
        type: number
      tokensHardCap:
        type: number
      beneficiaryAddress:
        type: string

  DeployCampaignTokenRequest:
    required:
      - amount
    properties: 
      amount:
        type: number
  
  DeployCampaignTokenFundraiserRequest:
    required:
      - address
    properties: 
      address:
        type: string
  
  ContractDeployedResponse:
    required:
      - address
      - abi
    properties: 
      address:
        type: string
      abi:
        type: array
        items: 
          $ref: "#/definitions/ABI"
  
  ABIInput:
    properties: 
      name:
        type: string
      type:
        type: string
  
  ABIOutput:
    properties: 
      name:
        type: string
      type:
        type: string
  ABI:
    properties: 
      constant:
        type: boolean
      name:
        type: string
      payable:
        type: boolean
      stateMutability:
        type: string
      type:
        type: string
      inputs:
        type: array
        items: 
          $ref: "#/definitions/ABIInput"
      outputs:
        type: array
        items: 
          $ref: "#/definitions/ABIOutput"